apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app
  namespace: default
  labels:
    app: sample-app
    environment: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::375976227140:role/dev-platform-dev-sample-app
